name: DEPLOY-GHP

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CI: false

jobs:
  build:
    if: github.event.head_commit.message  == 'Update package.json'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: "read"
      id-token: "write"
      pages: "write"
      actions: "write"
      checks: "write"
      deployments: "write"
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        # Using npm ci is generally faster than running npm i because it caches dependencies
        run: |
          npm install
      - name: Build the app
        run: |
          npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          enablement: true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload build directory content
          path: "dist/"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
